{
 "title": "Livebox",
 "tags": [ "livebox" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(livebox_nmc_wan_state, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "livebox_nmc_wan_state{job=\"$job\"}",
     "legendFormat": "WAN state (nmc)"
    }
   ]
  },
  {
   "title": "WAN current bit rate",
   "type": "bargauge",
   "description": "Computed data rate on WAN interface",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livebox_ont_rx_bit_rate{job=\"$job\"}",
     "legendFormat": "RX"
    },
    {
     "expr": "livebox_ont_tx_bit_rate{job=\"$job\"}",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "ONT throughput",
   "type": "bargauge",
   "description": "Current Optical Network Terminal (ONT) throughput",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "livebox_device_downstream_curr_rate{job=\"$job\"}",
     "legendFormat": "downstream"
    },
    {
     "expr": "livebox_device_upstream_curr_rate{job=\"$job\"}",
     "legendFormat": "upstream"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livebox_ont_temperature{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livebox_device_info_uptime{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboot count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livebox_device_info_reboots_total{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "WAN computed bit rate history",
   "type": "timeseries",
   "description": "Computed bit rate history on WAN interface",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "livebox_ont_rx_bit_rate{job=\"$job\"}",
     "legendFormat": "RX"
    },
    {
     "expr": "livebox_ont_tx_bit_rate{job=\"$job\"}",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Signal power",
   "type": "timeseries",
   "description": "Quality of ONT signal power.\nDash lines are good limits.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "livebox_ont_signal_rx_power{job=\"$job\"} / 1000",
     "legendFormat": "RX signal"
    },
    {
     "expr": "livebox_ont_signal_tx_power{job=\"$job\"} / 1000",
     "legendFormat": "TX signal"
    }
   ]
  },
  {
   "title": "ONT bias",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "livebox_ont_bias{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN stats",
   "type": "timeseries",
   "description": "Counters are cyclical. They are reset when they reach a threshold.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livebox_ont_rx_bytes{job=\"$job\"}",
     "legendFormat": "RX bytes"
    },
    {
     "expr": "livebox_ont_tx_bytes{job=\"$job\"}",
     "legendFormat": "TX bytes"
    },
    {
     "expr": "livebox_ont_rx_packets{job=\"$job\"}",
     "legendFormat": "RX packets"
    },
    {
     "expr": "livebox_ont_tx_packets{job=\"$job\"}",
     "legendFormat": "TX packets"
    }
   ]
  },
  {
   "title": "WAN Error Stats",
   "type": "timeseries",
   "description": "WAN error stats",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livebox_ont_rx_errors{job=\"$job\"}",
     "legendFormat": "RX errors"
    },
    {
     "expr": "livebox_ont_tx_errors{job=\"$job\"}",
     "legendFormat": "TX errors"
    },
    {
     "expr": "livebox_ont_rx_dropped{job=\"$job\"}",
     "legendFormat": "RX dropped"
    },
    {
     "expr": "livebox_ont_tx_dropped{job=\"$job\"}",
     "legendFormat": "TX dropped"
    },
    {
     "expr": "livebox_ont_multicast{job=\"$job\"}",
     "legendFormat": "multicast"
    },
    {
     "expr": "livebox_ont_collisions{job=\"$job\"}",
     "legendFormat": "collisions"
    },
    {
     "expr": "livebox_ont_rx_length_errors{job=\"$job\"}",
     "legendFormat": "RX length errors"
    },
    {
     "expr": "livebox_ont_rx_over_errors{job=\"$job\"}",
     "legendFormat": "RX Over errors"
    },
    {
     "expr": "livebox_ont_rx_crc_errors{job=\"$job\"}",
     "legendFormat": "RX CRC errors"
    },
    {
     "expr": "livebox_ont_rx_frame_errors{job=\"$job\"}",
     "legendFormat": "RX frame errors"
    },
    {
     "expr": "livebox_ont_rx_fifo_errors{job=\"$job\"}",
     "legendFormat": "RX FIFO errors"
    },
    {
     "expr": "livebox_ont_rx_missed_errors{job=\"$job\"}",
     "legendFormat": "RX missed errors"
    },
    {
     "expr": "livebox_ont_tx_aborted_errors{job=\"$job\"}",
     "legendFormat": "TX aborted errors"
    },
    {
     "expr": "livebox_ont_tx_carrier_errors{job=\"$job\"}",
     "legendFormat": "TX carrier errors"
    },
    {
     "expr": "livebox_ont_tx_fifo_errors{job=\"$job\"}",
     "legendFormat": "TX FIFO errors"
    },
    {
     "expr": "livebox_ont_tx_heartbeat_errors{job=\"$job\"}",
     "legendFormat": "TX heartbeat errors"
    },
    {
     "expr": "livebox_ont_tx_window_errors{job=\"$job\"}",
     "legendFormat": "TX window errors"
    }
   ]
  },
  {
   "title": "ONT throughput history",
   "type": "timeseries",
   "description": "Optical Network Terminal (ONT) throughput",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "livebox_device_downstream_max_bit_rate{job=\"$job\"}",
     "legendFormat": "downstream max throughput"
    },
    {
     "expr": "livebox_device_downstream_curr_rate{job=\"$job\"}",
     "legendFormat": "downstream current throughput"
    },
    {
     "expr": "livebox_device_upstream_max_bit_rate{job=\"$job\"}",
     "legendFormat": "upstream max throughput"
    },
    {
     "expr": "livebox_device_upstream_curr_rate{job=\"$job\"}",
     "legendFormat": "upstream current throughput"
    }
   ]
  },
  {
   "title": "Livebox status history",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livebox_device_info_status{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "States",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livebox_device_connection_state{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "livebox_nmc_connection_state{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "livebox_nmc_gpon_state{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "livebox_device_link_state{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "livebox_nmc_wan_state{job=\"$job\"}",
     "legendFormat": "WAN state (nmc)"
    },
    {
     "expr": "livebox_device_info_status{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter status",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livebox_exporter_up{job=\"$job\"}",
     "legendFormat": "Exporter OK"
    },
    {
     "expr": "livebox_exporter_metrics_up{job=\"$job\"}",
     "legendFormat": "Metrics are consistent"
    }
   ]
  }
 ]
}